version: 0.2

phases:
  install:
    commands:
        - /bin/bash -l -c "gem install bundler -v 1.17.3"
        - /bin/bash -l -c "bundle install"

        - cd terraform && terraform init
        - cd terraform && terraform apply -var="RDS_USERNAME_TEST=${RDS_USERNAME_TEST}" -var="RDS_PASSWORD_TEST=${RDS_PASSWORD_TEST}" -var="RDS_USERNAME=${RDS_USERNAME}" -var="RDS_PASSWORD=${RDS_PASSWORD}" -var="SECRET_KEY_BASE=${SECRET_KEY_BASE}" -auto-approve
        - chmod -x terraform/export_var.sh && . ./terraform/export_var.sh

  pre_build:
    commands:
        - /bin/bash -l -c "bundle exec rake db:drop RAILS_ENV=test"
        - /bin/bash -l -c "bundle exec rake db:create RAILS_ENV=test"
        - /bin/bash -l -c "bundle exec rake db:migrate RAILS_ENV=test"
  build:
    commands:
        - /bin/bash -l -c "bundle exec rspec --exclude-pattern '//*pictures*'"
